# Generated by Django 2.2.4 on 2019-08-06 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crawler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('url', models.CharField(max_length=200)),
                ('articles', models.CharField(max_length=200)),
                ('article_id', models.CharField(max_length=200)),
                ('article_url', models.CharField(max_length=200)),
                ('article_title', models.CharField(blank=True, max_length=200, null=True)),
                ('article_image', models.CharField(blank=True, max_length=200, null=True)),
                ('article_description', models.CharField(blank=True, max_length=200, null=True)),
                ('article_price', models.CharField(blank=True, max_length=200, null=True)),
                ('next_page_url', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_url', models.CharField(max_length=200)),
                ('time_interval', models.PositiveIntegerField(default=30)),
                ('timestamp', models.DateTimeField(blank=True, default=None, null=True)),
                ('active', models.BooleanField(default=True)),
                ('crawler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawlers.Crawler')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.CharField(max_length=200)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawlers.Task')),
            ],
            options={
                'unique_together': {('task', 'article_id')},
            },
        ),
    ]
