# Generated by Django 2.2.4 on 2019-08-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawlers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='search_url',
            field=models.CharField(max_length=2000),
        ),
    ]
